# Generated by Django 4.1.7 on 2023-05-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShieldX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrelatives',
            name='userRelativeImage',
            field=models.ImageField(default=1, upload_to='img/relatives'),
            preserve_default=False,
        ),
    ]
