# Generated by Django 4.1.7 on 2023-06-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
