# Generated by Django 4.1.7 on 2023-05-11 07:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 7, 25, 18, 240439, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
