# Generated by Django 4.1.7 on 2023-05-11 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0022_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 11, 17, 0, 49, 239667, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
