# Generated by Django 4.1.7 on 2023-04-02 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_checkout_checkout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='city',
            field=models.CharField(choices=[('AH', 'Ahmedabad'), ('SU', 'Surat')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkout',
            name='state',
            field=models.CharField(choices=[('GJ', 'Gujarat'), ('Delhi', 'DH')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 11, 15, 56, 121053, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
