# Generated by Django 4.1.7 on 2023-04-02 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_alter_checkout_checkout_date_alter_checkout_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 2, 12, 25, 2, 793966, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
