# Generated by Django 4.1.7 on 2023-04-28 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0021_rename_orderprice_checkout_totalorderprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 28, 9, 40, 58, 615824, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
