# Generated by Django 4.1.7 on 2023-04-29 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0024_alter_checkout_checkout_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 29, 11, 22, 48, 646651, tzinfo=datetime.timezone.utc), verbose_name='expiration time (of ad)'),
        ),
    ]
